version: "2"
services:
  postgres:
    build:
      context: services\postgres
      dockerfile: Dockerfile.development
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "db-data:/var/lib/postgresql/data"

  client:
    build:
      context: services\app
      dockerfile: Dockerfile.development
    environment:
      - PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/postgres
      - JS_URL=http://localhost
    image: 'maerodrim/chmmf'
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  db-data:
